### ISSUE TITLE
cnn_daily_load.py

### ISSUE THREAD

**Issue by sanjayb678** [DeepsMoseli/Bidirectiona-LSTM-for-text-summarization-#1]
1. local variables 'filenames' referenced before assignment in cnn_daily_load.py
2. Also, should the location be pointing to questions folder like below: CNN_data="C:\\Users\\moseli\\Documents\\Masters of Information technology\\Masters project\\text mining\\data\\new CNN\\cnn\\questions"

**Comment by DeepsMoseli** [comment]
Hi @sanjayb678 ,

thanks

on 1) , that shouldnt be the case as all function definitions are before their calls and 'filenames' is assigned for the first time on line 97, then used on line 100 

on 2) the version of the data i use isn't split is questions & answers folders. they are all in one folder named to sit one after the other like below
![image](https://user-images.githubusercontent.com/29062994/44058447-6ced07c6-9f4e-11e8-93c4-b244a0f3b09d.png)

let me know if this makes sense

**Comment by sanjayb678** [comment]
Thanks. Sorted this out. Got access to the correct data
