### ISSUE TITLE
Getting the same result for all articles !

### ISSUE THREAD

**Issue by abdullahfde** [DeepsMoseli/Bidirectiona-LSTM-for-text-summarization-#6]
I trained your code 20k with articles , it gives me the same summary for all articles ?
what is your results ?

**Comment by xinmin323** [comment]
results like this" islamists islamists islamists islamists islamists islamists islamists islamists islamists islamists islamists islamists islamists islamists islamists " ,why?

**Comment by abdullahfde** [comment]
The code is wrong don't  use it
